version: '3.8'
services:
  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
      - PORT_APP=5000
      - MONGODB_HOST="mongodb"
    volumes:
    - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - .dbdata:/mongodb
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  mongodb_network:
    name: mongodb_network
